image: gitpod/workspace-dotnet

# Commands that will run on workspace start
tasks:
  - name: Setup, Install & Build
    command: dotnet run  -- preview

# Ports to expose on workspace startup
ports:
  - port: 5080
    onOpen: open-preview
    name: Website
    description: Website Preview